server:
  port: 8080

spring:
  application:
    name: chat-backend

  datasource:
    data:
      mongodb:
        uri: mongodb://localhost:27017/karu


frontend:
  url: http://localhost:5173/chat-frontend/